# Generated by Django 3.2.4 on 2021-06-08 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='blog',
        ),
    ]
